INSERT INTO answer_correct_combinations VALUES (1);
INSERT INTO answer_correct_combinations VALUES (2);
INSERT INTO answer_correct_combinations VALUES (3);
INSERT INTO answer_correct_combinations VALUES (4);
INSERT INTO answer_correct_combinations VALUES (5);
INSERT INTO answer_correct_combinations VALUES (6);
INSERT INTO answer_correct_combinations VALUES (7);
INSERT INTO answer_correct_combinations VALUES (8);
INSERT INTO answer_correct_combinations VALUES (9);
INSERT INTO answer_correct_combinations VALUES (10);
INSERT INTO question VALUES (1, 1, '1 + 1 =');
INSERT INTO question VALUES (2, 2, '2 + 2 =');
INSERT INTO question VALUES (3, 3, '3 + 3 =');
INSERT INTO question VALUES (4, 4, '4 + 4 =');
INSERT INTO question VALUES (5, 5, '5 + 5 =');
INSERT INTO question VALUES (6, 6, '6 + 6 =');
INSERT INTO question VALUES (7, 7, '7 + 7 =');
INSERT INTO question VALUES (8, 8, '8 + 8 =');
INSERT INTO question VALUES (9, 9, '9 + 9 =');
INSERT INTO question VALUES (10, 10, '10 + 10 =');
INSERT INTO answer VALUES (2, 1, 1, '2');
INSERT INTO answer VALUES (1, NULL, 1, '3');
INSERT INTO answer VALUES (3, NULL, 1, '0');
INSERT INTO answer VALUES (4, 2, 2, '4');
INSERT INTO answer VALUES (5, 2, 2, '3 + 1');
INSERT INTO answer VALUES (6, NULL, 2, '10');
INSERT INTO answer VALUES (7, 3, 3, '1 + 5');
INSERT INTO answer VALUES (8, NULL, 3, '1');
INSERT INTO answer VALUES (9, 3, 3, '6');
INSERT INTO answer VALUES (10, 3, 3, '2 + 4');
INSERT INTO answer VALUES (11, 4, 4, '8');
INSERT INTO answer VALUES (12, NULL, 4, '4');
INSERT INTO answer VALUES (13, NULL, 4, '0');
INSERT INTO answer VALUES (14, 4, 4, '0 + 8');
INSERT INTO answer VALUES (17, 5, 5, '10');
INSERT INTO answer VALUES (16, NULL, 5, '18');
INSERT INTO answer VALUES (15, NULL, 5, '6');
INSERT INTO answer VALUES (18, NULL, 5, '9');
INSERT INTO answer VALUES (19, NULL, 5, '0');
INSERT INTO answer VALUES (23, 6, 6, '12');
INSERT INTO answer VALUES (22, NULL, 6, '0');
INSERT INTO answer VALUES (21, NULL, 6, '9');
INSERT INTO answer VALUES (20, NULL, 6, '3');
INSERT INTO answer VALUES (24, 6, 6, '5 + 7');
INSERT INTO answer VALUES (26, 7, 7, '14');
INSERT INTO answer VALUES (25, NULL, 7, '5');
INSERT INTO answer VALUES (27, 8, 8, '16');
INSERT INTO answer VALUES (28, NULL, 8, '12');
INSERT INTO answer VALUES (29, NULL, 8, '9');
INSERT INTO answer VALUES (30, NULL, 8, '5');
INSERT INTO answer VALUES (31, 9, 9, '18');
INSERT INTO answer VALUES (32, NULL, 9, '9');
INSERT INTO answer VALUES (33, 9, 9, '17 + 1');
INSERT INTO answer VALUES (34, 9, 9, '2 + 16');
INSERT INTO answer VALUES (38, 10, 10, '20');
INSERT INTO answer VALUES (37, NULL, 10, '8');
INSERT INTO answer VALUES (36, NULL, 10, '2');
INSERT INTO answer VALUES (35, NULL, 10, '0');
